# языки
TRANSLATION = {
    "ru": {
        "installation": "Установка",
        "welcome": "Вас приветсвует Мастер установки {name}",
        "welcome_info": "Программа установит {name}, версия {version} на ваш компьютер. \n\nРекомендуеться закрыть все прочие приложения перед тем, как продолжить. \n\nНажмите «Далее» что бы продолжить, или «Отмена», что бы выйте из программы установки.",
        "license": "Лицензионное Соглашение",
        "license_info": "Прочитайте и примите лицензтонное соглащение, что бы продолжить установку",
        "license_agree": "Я принимаю условия лицензионного соглашения",
        "path": "Выбор папки установки",
        "path_info": "В какую папку вы хотите установить {name}?",
        "path_agree": "Нажмите «Далее», что бы продолжить. Если вы хотите выбрать другую папку, нажмите «Обзор».",
        "path_size": "Требуется как минимум {size} {byts} свободного диского пространства.",
        "additionally": "Выберите дополнительное задачи",
        "additionally_info": "Какие дополнительное задачи необходимо выполнить?",
        "additionally_agree": "Выберите дополнительные задачи, которые должны выполниться при установке {name}, после этого нажмите «Далее»:",
        "additionally_options": "Дополнительные опции:",
        "additionally-icon": "Иконка игры на рабочем столе",
        "additionally-driver": "Установка нужных драйверов",
        "done": "Все готово к установке",
        "done_info": "Программа установки готова начать установку {name} на ваш компьютер.",
        "done_agree": "Нажмите «Установить», что бы продолжить.",
        "done_agree_tasks": "Нажмите «Установить», что бы продолжить, или «Назад», если вы хотите просмотреть или изменить опции установки.",
        "done_tasks": "Дополнительные задачи:",
        "installation_info": "Пожалуйста, подождите, пока {name} установиться на ваш компьютер.",
        "installation_agree-install": "Установка...",
        "installation_agree-install_driver": "Установка пакетов...",
        "installation_agree-unpacking": "Распаковка файлов...",
        "installation_agree-options": "Выполнение опций...",
        "completion": "Завершение Мастера установки {name}",
        "completion_info": "Программа {name} установлена на ваш компьютер.\nПриложение можно запустить с помощью определеного значка.",
        "completion_agree": "Нажмите «Завершить», чтобы выйте из программы установки.",
        "completion-icon": "Запустить {name}",
        "exit": "Выход из программы установки",
        "exit_info": "Установка не завершена. Если вы выйдете, программа не будет установлена.\n\nВы сможете завершить установку, запустив программу установки позже. \n\nВыйти из программы установки?",
        "yes": "Да",
        "no": "Нет",
        "further": "Далее",
        "complete": "Завершить",
        "install": "Установить",
        "cancellation": "Отмена",
        "back": "Назад",
        "review": "Обзор...",
        "name": "Русский",
        "units": ["КБ", "МБ", "ГБ", "ТБ", "ПБ"],
        "byte": "Б"
    },

    "en": {
        "installation": "Installation",
        "welcome": "Welcome to the {name} Setup Wizard",
        "welcome_info": "This will install {name}, version {version}, on your computer. \n\nIt is recommended that you close all other applications before continuing. \n\nClick \"Next\" to continue, or \"Cancel\" to exit Setup.",
        "license": "License Agreement",
        "license_info": "Please read and accept the license agreement to continue installation",
        "license_agree": "I accept the terms of the license agreement",
        "path": "Select Destination Location",
        "path_info": "Where would you like {name} to be installed?",
        "path_agree": "Click \"Next\" to continue. If you would like to select a different folder, click \"Browse\".",
        "path_size": "At least {size} {byts} of free disk space is required.",
        "additionally": "Select Additional Tasks",
        "additionally_info": "Which additional tasks would you like to perform?",
        "additionally_agree": "Select the additional tasks you would like Setup to perform while installing {name}, then click \"Next\":",
        "additionally_options": "Additional options:",
        "additionally-icon": "Create a desktop shortcut",
        "additionally-driver": "Install required drivers",
        "done": "Ready to Install",
        "done_info": "Setup is now ready to begin installing {name} on your computer.",
        "done_agree": "Click \"Install\" to continue.",
        "done_agree_tasks": "Click \"Install\" to continue, or click \"Back\" if you want to review or change any settings.",
        "done_tasks": "Additional tasks:",
        "installation_info": "Please wait while {name} is installed on your computer.",
        "installation_agree-install": "Installing...",
        "installation_agree-install_driver": "Installing packages...",
        "installation_agree-unpacking": "Extracting files...",
        "installation_agree-options": "Performing options...",
        "completion": "Completing the {name} Setup Wizard",
        "completion_info": "{name} has been installed on your computer.\nThe application can be launched using the shortcut.",
        "completion_agree": "Click \"Finish\" to exit Setup.",
        "completion-icon": "Launch {name}",
        "exit": "Exit Setup",
        "exit_info": "Setup is not complete. If you exit now, the program will not be installed.\n\nYou can run Setup again later to complete the installation. \n\nExit Setup?",
        "yes": "Yes",
        "no": "No",
        "further": "Next",
        "complete": "Finish",
        "install": "Install",
        "cancellation": "Cancel",
        "back": "Back",
        "review": "Browse...",
        "name": "English",
        "units": ["KB", "MB", "GB", "TB", "PB"],
        "byte": "B"
    },

    "es": {
        "installation": "Instalación",
        "welcome": "Bienvenido al Asistente de instalación de {name}",
        "welcome_info": "Este programa instalará {name}, versión {version}, en su equipo. \n\nSe recomienda cerrar todas las demás aplicaciones antes de continuar. \n\nHaga clic en «Siguiente» para continuar, o en «Cancelar» para salir del instalador.",
        "license": "Contrato de Licencia",
        "license_info": "Lea y acepte el contrato de licencia para continuar con la instalación",
        "license_agree": "Acepto los términos del contrato de licencia",
        "path": "Seleccionar carpeta de destino",
        "path_info": "¿En qué carpeta desea instalar {name}?",
        "path_agree": "Haga clic en «Siguiente» para continuar. Si desea elegir otra carpeta, haga clic en «Examinar».",
        "path_size": "Se requiere al menos {size} {byts} de espacio libre en disco.",
        "additionally": "Seleccionar tareas adicionales",
        "additionally_info": "¿Qué tareas adicionales desea realizar?",
        "additionally_agree": "Seleccione las tareas adicionales que desea realizar durante la instalación de {name} y luego haga clic en «Siguiente»:",
        "additionally_options": "Opciones adicionales:",
        "additionally-icon": "Crear icono en el escritorio",
        "additionally-driver": "Instalar los controladores necesarios",
        "done": "Listo para instalar",
        "done_info": "El instalador está listo para comenzar a instalar {name} en su equipo.",
        "done_agree": "Haga clic en «Instalar» para continuar.",
        "done_agree_tasks": "Haga clic en «Instalar» para continuar, o en «Atrás» si desea revisar o cambiar alguna configuración.",
        "done_tasks": "Tareas adicionales:",
        "installation_info": "Espere mientras se instala {name} en su equipo.",
        "installation_agree-install": "Instalando...",
        "installation_agree-install_driver": "Instalando paquetes...",
        "installation_agree-unpacking": "Extrayendo archivos...",
        "installation_agree-options": "Aplicando opciones...",
        "completion": "Finalización del Asistente de instalación de {name}",
        "completion_info": "{name} se ha instalado en su equipo.\nPuede iniciar la aplicación mediante el icono correspondiente.",
        "completion_agree": "Haga clic en «Finalizar» para salir del instalador.",
        "completion-icon": "Iniciar {name}",
        "exit": "Salir del instalador",
        "exit_info": "La instalación no se ha completado. Si sale ahora, el programa no se instalará.\n\nPodrá completar la instalación ejecutando el instalador más tarde. \n\n¿Salir del instalador?",
        "yes": "Sí",
        "no": "No",
        "further": "Siguiente",
        "complete": "Finalizar",
        "install": "Instalar",
        "cancellation": "Cancelar",
        "back": "Atrás",
        "review": "Examinar...",
        "name": "Español",
        "units": ["KB", "MB", "GB", "TB", "PB"],
        "byte": "B"
    },

    "fr": {
        "installation": "Installation",
        "welcome": "Bienvenue dans l'Assistant d'installation de {name}",
        "welcome_info": "Ce programme va installer {name}, version {version}, sur votre ordinateur. \n\nIl est recommandé de fermer toutes les autres applications avant de continuer. \n\nCliquez sur « Suivant » pour continuer, ou sur « Annuler » pour quitter l'installation.",
        "license": "Contrat de licence",
        "license_info": "Veuillez lire et accepter le contrat de licence pour poursuivre l'installation",
        "license_agree": "J'accepte les termes du contrat de licence",
        "path": "Choix du dossier de destination",
        "path_info": "Dans quel dossier souhaitez-vous installer {name} ?",
        "path_agree": "Cliquez sur « Suivant » pour continuer. Si vous souhaitez choisir un autre dossier, cliquez sur « Parcourir ».",
        "path_size": "Au moins {size} {byts} d'espace disque libre sont requis.",
        "additionally": "Sélection des tâches supplémentaires",
        "additionally_info": "Quelles tâches supplémentaires souhaitez-vous effectuer ?",
        "additionally_agree": "Sélectionnez les tâches supplémentaires à effectuer lors de l'installation de {name}, puis cliquez sur « Suivant » :",
        "additionally_options": "Options supplémentaires :",
        "additionally-icon": "Créer une icône sur le bureau",
        "additionally-driver": "Installer les pilotes nécessaires",
        "done": "Prêt à installer",
        "done_info": "Le programme d'installation est prêt à commencer l'installation de {name} sur votre ordinateur.",
        "done_agree": "Cliquez sur « Installer » pour continuer.",
        "done_agree_tasks": "Cliquez sur « Installer » pour continuer, ou sur « Précédent » pour revoir ou modifier les options.",
        "done_tasks": "Tâches supplémentaires :",
        "installation_info": "Veuillez patienter pendant l'installation de {name} sur votre ordinateur.",
        "installation_agree-install": "Installation en cours...",
        "installation_agree-install_driver": "Installation des paquets...",
        "installation_agree-unpacking": "Extraction des fichiers...",
        "installation_agree-options": "Application des options...",
        "completion": "Fin de l'Assistant d'installation de {name}",
        "completion_info": "{name} a été installé sur votre ordinateur.\nVous pouvez lancer l'application à l'aide du raccourci correspondant.",
        "completion_agree": "Cliquez sur « Terminer » pour quitter l'installation.",
        "completion-icon": "Lancer {name}",
        "exit": "Quitter l'installation",
        "exit_info": "L'installation n'est pas terminée. Si vous quittez maintenant, le programme ne sera pas installé.\n\nVous pourrez terminer l'installation en relançant le programme plus tard. \n\nQuitter l'installation ?",
        "yes": "Oui",
        "no": "Non",
        "further": "Suivant",
        "complete": "Terminer",
        "install": "Installer",
        "cancellation": "Annuler",
        "back": "Précédent",
        "review": "Parcourir...",
        "name": "Français",
        "units": ["Ko", "Mo", "Go", "To", "Po"],
        "byte": "o"
    },

    "de": {
        "installation": "Installation",
        "welcome": "Willkommen beim {name} Setup-Assistenten",
        "welcome_info": "Dieses Programm installiert {name}, Version {version}, auf Ihrem Computer. \n\nEs wird empfohlen, alle anderen Anwendungen zu schließen, bevor Sie fortfahren. \n\nKlicken Sie auf „Weiter“, um fortzufahren, oder auf „Abbrechen“, um das Setup zu beenden.",
        "license": "Lizenzvereinbarung",
        "license_info": "Bitte lesen und akzeptieren Sie die Lizenzvereinbarung, um mit der Installation fortzufahren",
        "license_agree": "Ich akzeptiere die Bedingungen der Lizenzvereinbarung",
        "path": "Zielordner auswählen",
        "path_info": "In welchem Ordner möchten Sie {name} installieren?",
        "path_agree": "Klicken Sie auf „Weiter“, um fortzufahren. Wenn Sie einen anderen Ordner wählen möchten, klicken Sie auf „Durchsuchen“.",
        "path_size": "Es wird mindestens {size} {byts} freier Speicherplatz benötigt.",
        "additionally": "Zusätzliche Aufgaben auswählen",
        "additionally_info": "Welche zusätzlichen Aufgaben möchten Sie ausführen?",
        "additionally_agree": "Wählen Sie die zusätzlichen Aufgaben aus, die bei der Installation von {name} ausgeführt werden sollen, und klicken Sie dann auf „Weiter“:",
        "additionally_options": "Zusätzliche Optionen:",
        "additionally-icon": "Desktop-Symbol erstellen",
        "additionally-driver": "Erforderliche Treiber installieren",
        "done": "Bereit zur Installation",
        "done_info": "Das Setup ist bereit, {name} auf Ihrem Computer zu installieren.",
        "done_agree": "Klicken Sie auf „Installieren“, um fortzufahren.",
        "done_agree_tasks": "Klicken Sie auf „Installieren“, um fortzufahren, oder auf „Zurück“, um Einstellungen zu überprüfen oder zu ändern.",
        "done_tasks": "Zusätzliche Aufgaben:",
        "installation_info": "Bitte warten Sie, während {name} auf Ihrem Computer installiert wird.",
        "installation_agree-install": "Wird installiert...",
        "installation_agree-install_driver": "Pakete werden installiert...",
        "installation_agree-unpacking": "Dateien werden entpackt...",
        "installation_agree-options": "Optionen werden ausgeführt...",
        "completion": "Abschluss des {name} Setup-Assistenten",
        "completion_info": "{name} wurde auf Ihrem Computer installiert.\nDie Anwendung kann über das entsprechende Symbol gestartet werden.",
        "completion_agree": "Klicken Sie auf „Fertigstellen“, um das Setup zu beenden.",
        "completion-icon": "{name} starten",
        "exit": "Setup beenden",
        "exit_info": "Die Installation ist nicht abgeschlossen. Wenn Sie jetzt beenden, wird das Programm nicht installiert.\n\nSie können das Setup später erneut ausführen, um die Installation abzuschließen. \n\nSetup beenden?",
        "yes": "Ja",
        "no": "Nein",
        "further": "Weiter",
        "complete": "Fertigstellen",
        "install": "Installieren",
        "cancellation": "Abbrechen",
        "back": "Zurück",
        "review": "Durchsuchen...",
        "name": "Deutsch",
        "units": ["KB", "MB", "GB", "TB", "PB"],
        "byte": "B"
    },

    "it": {
        "installation": "Installazione",
        "welcome": "Benvenuti nella Procedura guidata di installazione di {name}",
        "welcome_info": "Questo programma installerà {name}, versione {version}, sul computer. \n\nSi consiglia di chiudere tutte le altre applicazioni prima di continuare. \n\nFare clic su «Avanti» per continuare, oppure su «Annulla» per uscire dall'installazione.",
        "license": "Contratto di licenza",
        "license_info": "Leggere e accettare il contratto di licenza per proseguire con l'installazione",
        "license_agree": "Accetto i termini del contratto di licenza",
        "path": "Selezione della cartella di destinazione",
        "path_info": "In quale cartella si desidera installare {name}?",
        "path_agree": "Fare clic su «Avanti» per continuare. Per selezionare una cartella diversa, fare clic su «Sfoglia».",
        "path_size": "Sono richiesti almeno {size} {byts} di spazio libero su disco.",
        "additionally": "Selezione delle attività aggiuntive",
        "additionally_info": "Quali attività aggiuntive si desidera eseguire?",
        "additionally_agree": "Selezionare le attività aggiuntive da eseguire durante l'installazione di {name}, quindi fare clic su «Avanti»:",
        "additionally_options": "Opzioni aggiuntive:",
        "additionally-icon": "Crea icona sul desktop",
        "additionally-driver": "Installa i driver necessari",
        "done": "Pronto per l'installazione",
        "done_info": "Il programma di installazione è pronto per iniziare a installare {name} sul computer.",
        "done_agree": "Fare clic su «Installa» per continuare.",
        "done_agree_tasks": "Fare clic su «Installa» per continuare, oppure su «Indietro» per rivedere o modificare le impostazioni.",
        "done_tasks": "Attività aggiuntive:",
        "installation_info": "Attendere durante l'installazione di {name} sul computer.",
        "installation_agree-install": "Installazione in corso...",
        "installation_agree-install_driver": "Installazione dei pacchetti...",
        "installation_agree-unpacking": "Estrazione dei file...",
        "installation_agree-options": "Applicazione delle opzioni...",
        "completion": "Completamento della Procedura guidata di installazione di {name}",
        "completion_info": "{name} è stato installato sul computer.\nÈ possibile avviare l'applicazione tramite l'apposita icona.",
        "completion_agree": "Fare clic su «Fine» per uscire dall'installazione.",
        "completion-icon": "Avvia {name}",
        "exit": "Esci dall'installazione",
        "exit_info": "L'installazione non è completa. Se si esce ora, il programma non verrà installato.\n\nSarà possibile completare l'installazione eseguendo nuovamente il programma in seguito. \n\nUscire dall'installazione?",
        "yes": "Sì",
        "no": "No",
        "further": "Avanti",
        "complete": "Fine",
        "install": "Installa",
        "cancellation": "Annulla",
        "back": "Indietro",
        "review": "Sfoglia...",
        "name": "Italiano",
        "units": ["KB", "MB", "GB", "TB", "PB"],
        "byte": "B"
    },

    "pt": {
        "installation": "Instalação",
        "welcome": "Bem-vindo ao Assistente de Instalação do {name}",
        "welcome_info": "Este programa irá instalar o {name}, versão {version}, no seu computador. \n\nRecomenda-se fechar todos os outros aplicativos antes de continuar. \n\nClique em «Avançar» para continuar, ou em «Cancelar» para sair do instalador.",
        "license": "Contrato de Licença",
        "license_info": "Leia e aceite o contrato de licença para continuar com a instalação",
        "license_agree": "Aceito os termos do contrato de licença",
        "path": "Selecionar pasta de destino",
        "path_info": "Em qual pasta deseja instalar o {name}?",
        "path_agree": "Clique em «Avançar» para continuar. Se quiser escolher outra pasta, clique em «Procurar».",
        "path_size": "É necessário pelo menos {size} {byts} de espaço livre em disco.",
        "additionally": "Selecionar tarefas adicionais",
        "additionally_info": "Quais tarefas adicionais deseja executar?",
        "additionally_agree": "Selecione as tarefas adicionais a executar durante a instalação do {name} e clique em «Avançar»:",
        "additionally_options": "Opções adicionais:",
        "additionally-icon": "Criar ícone na área de trabalho",
        "additionally-driver": "Instalar os drivers necessários",
        "done": "Pronto para instalar",
        "done_info": "O instalador está pronto para iniciar a instalação do {name} no seu computador.",
        "done_agree": "Clique em «Instalar» para continuar.",
        "done_agree_tasks": "Clique em «Instalar» para continuar, ou em «Voltar» para rever ou alterar as configurações.",
        "done_tasks": "Tarefas adicionais:",
        "installation_info": "Aguarde enquanto o {name} é instalado no seu computador.",
        "installation_agree-install": "Instalando...",
        "installation_agree-install_driver": "Instalando pacotes...",
        "installation_agree-unpacking": "Extraindo arquivos...",
        "installation_agree-options": "Aplicando opções...",
        "completion": "Conclusão do Assistente de Instalação do {name}",
        "completion_info": "O {name} foi instalado no seu computador.\nO aplicativo pode ser iniciado através do ícone correspondente.",
        "completion_agree": "Clique em «Concluir» para sair do instalador.",
        "completion-icon": "Iniciar {name}",
        "exit": "Sair do instalador",
        "exit_info": "A instalação não foi concluída. Se sair agora, o programa não será instalado.\n\nPoderá concluir a instalação executando o instalador novamente mais tarde. \n\nSair do instalador?",
        "yes": "Sim",
        "no": "Não",
        "further": "Avançar",
        "complete": "Concluir",
        "install": "Instalar",
        "cancellation": "Cancelar",
        "back": "Voltar",
        "review": "Procurar...",
        "name": "Português",
        "units": ["KB", "MB", "GB", "TB", "PB"],
        "byte": "B"
    },

    "zh": {
        "installation": "安装",
        "welcome": "欢迎使用 {name} 安装向导",
        "welcome_info": "此程序将在您的计算机上安装 {name}，版本 {version}。\n\n建议您在继续之前关闭所有其他应用程序。\n\n单击“下一步”继续，或单击“取消”退出安装程序。",
        "license": "许可协议",
        "license_info": "请阅读并接受许可协议以继续安装",
        "license_agree": "我接受许可协议的条款",
        "path": "选择安装位置",
        "path_info": "您希望将 {name} 安装到哪个文件夹？",
        "path_agree": "单击“下一步”继续。如果您想选择其他文件夹，请单击“浏览”。",
        "path_size": "至少需要 {size} {byts} 的可用磁盘空间。",
        "additionally": "选择附加任务",
        "additionally_info": "您希望执行哪些附加任务？",
        "additionally_agree": "请选择在安装 {name} 时要执行的附加任务，然后单击“下一步”：",
        "additionally_options": "附加选项：",
        "additionally-icon": "创建桌面图标",
        "additionally-driver": "安装所需的驱动程序",
        "done": "准备安装",
        "done_info": "安装程序现已准备好在您的计算机上开始安装 {name}。",
        "done_agree": "单击“安装”继续。",
        "done_agree_tasks": "单击“安装”继续，或单击“上一步”查看或更改设置。",
        "done_tasks": "附加任务：",
        "installation_info": "请稍候，{name} 正在安装到您的计算机上。",
        "installation_agree-install": "正在安装…",
        "installation_agree-install_driver": "正在安装软件包…",
        "installation_agree-unpacking": "正在解压文件…",
        "installation_agree-options": "正在执行选项…",
        "completion": "{name} 安装向导已完成",
        "completion_info": "{name} 已安装到您的计算机上。\n您可以通过相应的图标启动该应用程序。",
        "completion_agree": "单击“完成”退出安装程序。",
        "completion-icon": "启动 {name}",
        "exit": "退出安装程序",
        "exit_info": "安装尚未完成。如果您现在退出，程序将不会被安装。\n\n您可以稍后重新运行安装程序以完成安装。\n\n是否退出安装程序？",
        "yes": "是",
        "no": "否",
        "further": "下一步",
        "complete": "完成",
        "install": "安装",
        "cancellation": "取消",
        "back": "上一步",
        "review": "浏览...",
        "name": "中文",
        "units": ["KB", "MB", "GB", "TB", "PB"],
        "byte": "B"
    },

    "ja": {
        "installation": "インストール",
        "welcome": "{name} セットアップウィザードへようこそ",
        "welcome_info": "このプログラムは {name}（バージョン {version}）をコンピューターにインストールします。\n\n続行する前に、他のすべてのアプリケーションを終了することをお勧めします。\n\n「次へ」をクリックして続行するか、「キャンセル」をクリックしてセットアップを終了してください。",
        "license": "使用許諾契約",
        "license_info": "インストールを続行するには、使用許諾契約をお読みいただき、同意してください",
        "license_agree": "使用許諾契約の条項に同意します",
        "path": "インストール先の選択",
        "path_info": "{name} をどのフォルダーにインストールしますか？",
        "path_agree": "「次へ」をクリックして続行してください。別のフォルダーを選択する場合は「参照」をクリックしてください。",
        "path_size": "少なくとも {size} {byts} の空きディスク容量が必要です。",
        "additionally": "追加タスクの選択",
        "additionally_info": "どの追加タスクを実行しますか？",
        "additionally_agree": "{name} のインストール時に実行する追加タスクを選択し、「次へ」をクリックしてください：",
        "additionally_options": "追加オプション：",
        "additionally-icon": "デスクトップにアイコンを作成する",
        "additionally-driver": "必要なドライバーをインストールする",
        "done": "インストールの準備完了",
        "done_info": "セットアップはコンピューターへの {name} のインストールを開始する準備が整いました。",
        "done_agree": "「インストール」をクリックして続行してください。",
        "done_agree_tasks": "「インストール」をクリックして続行するか、設定を確認・変更する場合は「戻る」をクリックしてください。",
        "done_tasks": "追加タスク：",
        "installation_info": "{name} をコンピューターにインストールしていますので、しばらくお待ちください。",
        "installation_agree-install": "インストール中...",
        "installation_agree-install_driver": "パッケージをインストール中...",
        "installation_agree-unpacking": "ファイルを展開中...",
        "installation_agree-options": "オプションを実行中...",
        "completion": "{name} セットアップウィザードの完了",
        "completion_info": "{name} がコンピューターにインストールされました。\nアプリケーションは対応するアイコンから起動できます。",
        "completion_agree": "「完了」をクリックしてセットアップを終了してください。",
        "completion-icon": "{name} を起動する",
        "exit": "セットアップを終了",
        "exit_info": "インストールが完了していません。今すぐ終了すると、プログラムはインストールされません。\n\nセットアップを後で再実行してインストールを完了することができます。\n\nセットアップを終了しますか？",
        "yes": "はい",
        "no": "いいえ",
        "further": "次へ",
        "complete": "完了",
        "install": "インストール",
        "cancellation": "キャンセル",
        "back": "戻る",
        "review": "参照...",
        "name": "日本語",
        "units": ["KB", "MB", "GB", "TB", "PB"],
        "byte": "B"
    },

    "ko": {
        "installation": "설치",
        "welcome": "{name} 설치 마법사에 오신 것을 환영합니다",
        "welcome_info": "이 프로그램은 {name} 버전 {version}을(를) 컴퓨터에 설치합니다. \n\n계속하기 전에 다른 모든 응용 프로그램을 닫는 것이 좋습니다. \n\n계속하려면 \"다음\"을 클릭하고, 설치를 종료하려면 \"취소\"를 클릭하세요.",
        "license": "사용권 계약",
        "license_info": "설치를 계속하려면 사용권 계약을 읽고 동의하세요",
        "license_agree": "사용권 계약의 조항에 동의합니다",
        "path": "설치 위치 선택",
        "path_info": "{name}을(를) 어느 폴더에 설치하시겠습니까?",
        "path_agree": "계속하려면 \"다음\"을 클릭하세요. 다른 폴더를 선택하려면 \"찾아보기\"를 클릭하세요.",
        "path_size": "최소 {size} {byts}의 여유 디스크 공간이 필요합니다.",
        "additionally": "추가 작업 선택",
        "additionally_info": "어떤 추가 작업을 수행하시겠습니까?",
        "additionally_agree": "{name} 설치 중에 수행할 추가 작업을 선택한 다음 \"다음\"을 클릭하세요:",
        "additionally_options": "추가 옵션:",
        "additionally-icon": "바탕 화면에 아이콘 만들기",
        "additionally-driver": "필요한 드라이버 설치",
        "done": "설치 준비 완료",
        "done_info": "설치 프로그램이 컴퓨터에 {name} 설치를 시작할 준비가 되었습니다.",
        "done_agree": "계속하려면 \"설치\"를 클릭하세요.",
        "done_agree_tasks": "계속하려면 \"설치\"를 클릭하고, 설정을 검토하거나 변경하려면 \"뒤로\"를 클릭하세요.",
        "done_tasks": "추가 작업:",
        "installation_info": "{name}을(를) 컴퓨터에 설치하는 동안 기다려 주세요.",
        "installation_agree-install": "설치 중...",
        "installation_agree-install_driver": "패키지 설치 중...",
        "installation_agree-unpacking": "파일 압축 해제 중...",
        "installation_agree-options": "옵션 적용 중...",
        "completion": "{name} 설치 마법사 완료",
        "completion_info": "{name}이(가) 컴퓨터에 설치되었습니다.\n해당 아이콘을 사용하여 응용 프로그램을 실행할 수 있습니다.",
        "completion_agree": "설치 프로그램을 종료하려면 \"마침\"을 클릭하세요.",
        "completion-icon": "{name} 실행",
        "exit": "설치 종료",
        "exit_info": "설치가 완료되지 않았습니다. 지금 종료하면 프로그램이 설치되지 않습니다.\n\n나중에 설치 프로그램을 다시 실행하여 설치를 완료할 수 있습니다. \n\n설치를 종료하시겠습니까?",
        "yes": "예",
        "no": "아니요",
        "further": "다음",
        "complete": "마침",
        "install": "설치",
        "cancellation": "취소",
        "back": "뒤로",
        "review": "찾아보기...",
        "name": "한국어",
        "units": ["KB", "MB", "GB", "TB", "PB"],
        "byte": "B"
    },

    "pl": {
        "installation": "Instalacja",
        "welcome": "Witamy w Kreatorze instalacji {name}",
        "welcome_info": "Ten program zainstaluje {name}, wersja {version}, na Twoim komputerze. \n\nZaleca się zamknięcie wszystkich innych aplikacji przed kontynuowaniem. \n\nKliknij «Dalej», aby kontynuować, lub «Anuluj», aby zakończyć instalację.",
        "license": "Umowa licencyjna",
        "license_info": "Przeczytaj i zaakceptuj umowę licencyjną, aby kontynuować instalację",
        "license_agree": "Akceptuję warunki umowy licencyjnej",
        "path": "Wybór folderu docelowego",
        "path_info": "W którym folderze chcesz zainstalować {name}?",
        "path_agree": "Kliknij «Dalej», aby kontynuować. Jeśli chcesz wybrać inny folder, kliknij «Przeglądaj».",
        "path_size": "Wymagane jest co najmniej {size} {byts} wolnego miejsca na dysku.",
        "additionally": "Wybór zadań dodatkowych",
        "additionally_info": "Jakie zadania dodatkowe chcesz wykonać?",
        "additionally_agree": "Wybierz zadania dodatkowe, które mają zostać wykonane podczas instalacji {name}, a następnie kliknij «Dalej»:",
        "additionally_options": "Opcje dodatkowe:",
        "additionally-icon": "Utwórz ikonę na pulpicie",
        "additionally-driver": "Zainstaluj wymagane sterowniki",
        "done": "Gotowy do instalacji",
        "done_info": "Instalator jest gotowy do rozpoczęcia instalacji {name} na Twoim komputerze.",
        "done_agree": "Kliknij «Instaluj», aby kontynuować.",
        "done_agree_tasks": "Kliknij «Instaluj», aby kontynuować, lub «Wstecz», aby przejrzeć lub zmienić ustawienia.",
        "done_tasks": "Zadania dodatkowe:",
        "installation_info": "Poczekaj, aż {name} zostanie zainstalowany na Twoim komputerze.",
        "installation_agree-install": "Instalowanie...",
        "installation_agree-install_driver": "Instalowanie pakietów...",
        "installation_agree-unpacking": "Rozpakowywanie plików...",
        "installation_agree-options": "Wykonywanie opcji...",
        "completion": "Zakończenie Kreatora instalacji {name}",
        "completion_info": "{name} został zainstalowany na Twoim komputerze.\nAplikację można uruchomić za pomocą odpowiedniej ikony.",
        "completion_agree": "Kliknij «Zakończ», aby zamknąć instalator.",
        "completion-icon": "Uruchom {name}",
        "exit": "Zakończ instalację",
        "exit_info": "Instalacja nie została zakończona. Jeśli teraz zakończysz, program nie zostanie zainstalowany.\n\nInstalację będzie można dokończyć, uruchamiając instalator później. \n\nZakończyć instalację?",
        "yes": "Tak",
        "no": "Nie",
        "further": "Dalej",
        "complete": "Zakończ",
        "install": "Instaluj",
        "cancellation": "Anuluj",
        "back": "Wstecz",
        "review": "Przeglądaj...",
        "name": "Polski",
        "units": ["KB", "MB", "GB", "TB", "PB"],
        "byte": "B"
    },

    "tr": {
        "installation": "Kurulum",
        "welcome": "{name} Kurulum Sihirbazına Hoş Geldiniz",
        "welcome_info": "Bu program {name} sürüm {version} bilgisayarınıza kuracaktır. \n\nDevam etmeden önce diğer tüm uygulamaları kapatmanız önerilir. \n\nDevam etmek için «İleri», kurulumdan çıkmak için «İptal» seçeneğine tıklayın.",
        "license": "Lisans Sözleşmesi",
        "license_info": "Kuruluma devam etmek için lisans sözleşmesini okuyun ve kabul edin",
        "license_agree": "Lisans sözleşmesinin şartlarını kabul ediyorum",
        "path": "Hedef Konumu Seçin",
        "path_info": "{name} hangi klasöre kurulsun?",
        "path_agree": "Devam etmek için «İleri»ye tıklayın. Farklı bir klasör seçmek isterseniz «Gözat»a tıklayın.",
        "path_size": "En az {size} {byts} boş disk alanı gereklidir.",
        "additionally": "Ek Görevleri Seçin",
        "additionally_info": "Hangi ek görevleri gerçekleştirmek istersiniz?",
        "additionally_agree": "{name} kurulurken gerçekleştirilecek ek görevleri seçin ve ardından «İleri»ye tıklayın:",
        "additionally_options": "Ek seçenekler:",
        "additionally-icon": "Masaüstünde simge oluştur",
        "additionally-driver": "Gerekli sürücüleri kur",
        "done": "Kuruluma Hazır",
        "done_info": "Kurulum, {name} programını bilgisayarınıza kurmaya hazır.",
        "done_agree": "Devam etmek için «Kur»a tıklayın.",
        "done_agree_tasks": "Devam etmek için «Kur»a, ayarları gözden geçirmek veya değiştirmek için «Geri»ye tıklayın.",
        "done_tasks": "Ek görevler:",
        "installation_info": "{name} bilgisayarınıza kurulurken lütfen bekleyin.",
        "installation_agree-install": "Kuruluyor...",
        "installation_agree-install_driver": "Paketler kuruluyor...",
        "installation_agree-unpacking": "Dosyalar ayıklanıyor...",
        "installation_agree-options": "Seçenekler uygulanıyor...",
        "completion": "{name} Kurulum Sihirbazı Tamamlanıyor",
        "completion_info": "{name} bilgisayarınıza kuruldu.\nUygulama ilgili simge kullanılarak başlatılabilir.",
        "completion_agree": "Kurulumdan çıkmak için «Bitir»e tıklayın.",
        "completion-icon": "{name} programını başlat",
        "exit": "Kurulumdan Çık",
        "exit_info": "Kurulum tamamlanmadı. Şimdi çıkarsanız, program kurulmayacaktır.\n\nKurulumu daha sonra tekrar çalıştırarak tamamlayabilirsiniz. \n\nKurulumdan çıkılsın mı?",
        "yes": "Evet",
        "no": "Hayır",
        "further": "İleri",
        "complete": "Bitir",
        "install": "Kur",
        "cancellation": "İptal",
        "back": "Geri",
        "review": "Gözat...",
        "name": "Türkçe",
        "units": ["KB", "MB", "GB", "TB", "PB"],
        "byte": "B"
    },

    "uk": {
        "installation": "Встановлення",
        "welcome": "Вітаємо в Майстрі встановлення {name}",
        "welcome_info": "Ця програма встановить {name}, версія {version}, на ваш комп'ютер. \n\nРекомендується закрити всі інші програми перед тим, як продовжити. \n\nНатисніть «Далі», щоб продовжити, або «Скасувати», щоб вийти з програми встановлення.",
        "license": "Ліцензійна угода",
        "license_info": "Прочитайте та прийміть ліцензійну угоду, щоб продовжити встановлення",
        "license_agree": "Я приймаю умови ліцензійної угоди",
        "path": "Вибір папки встановлення",
        "path_info": "У яку папку ви хочете встановити {name}?",
        "path_agree": "Натисніть «Далі», щоб продовжити. Якщо ви хочете вибрати іншу папку, натисніть «Огляд».",
        "path_size": "Потрібно щонайменше {size} {byts} вільного місця на диску.",
        "additionally": "Виберіть додаткові завдання",
        "additionally_info": "Які додаткові завдання потрібно виконати?",
        "additionally_agree": "Виберіть додаткові завдання, які слід виконати під час встановлення {name}, а потім натисніть «Далі»:",
        "additionally_options": "Додаткові опції:",
        "additionally-icon": "Значок гри на робочому столі",
        "additionally-driver": "Встановлення потрібних драйверів",
        "done": "Усе готово до встановлення",
        "done_info": "Програма встановлення готова розпочати встановлення {name} на ваш комп'ютер.",
        "done_agree": "Натисніть «Встановити», щоб продовжити.",
        "done_agree_tasks": "Натисніть «Встановити», щоб продовжити, або «Назад», якщо хочете переглянути чи змінити параметри.",
        "done_tasks": "Додаткові завдання:",
        "installation_info": "Будь ласка, зачекайте, поки {name} встановлюється на ваш комп'ютер.",
        "installation_agree-install": "Встановлення...",
        "installation_agree-install_driver": "Встановлення пакетів...",
        "installation_agree-unpacking": "Розпакування файлів...",
        "installation_agree-options": "Виконання опцій...",
        "completion": "Завершення Майстра встановлення {name}",
        "completion_info": "Програму {name} встановлено на ваш комп'ютер.\nЗастосунок можна запустити за допомогою відповідного значка.",
        "completion_agree": "Натисніть «Завершити», щоб вийти з програми встановлення.",
        "completion-icon": "Запустити {name}",
        "exit": "Вихід з програми встановлення",
        "exit_info": "Встановлення не завершено. Якщо ви вийдете, програму не буде встановлено.\n\nВи зможете завершити встановлення, запустивши програму встановлення пізніше. \n\nВийти з програми встановлення?",
        "yes": "Так",
        "no": "Ні",
        "further": "Далі",
        "complete": "Завершити",
        "install": "Встановити",
        "cancellation": "Скасувати",
        "back": "Назад",
        "review": "Огляд...",
        "name": "Українська",
        "units": ["КБ", "МБ", "ГБ", "ТБ", "ПБ"],
        "byte": "Б"
    },

    "ar": {
        "installation": "التثبيت",
        "welcome": "مرحبًا بك في معالج تثبيت {name}",
        "welcome_info": "سيقوم هذا البرنامج بتثبيت {name}، الإصدار {version}، على جهاز الكمبيوتر الخاص بك. \n\nيُنصح بإغلاق جميع التطبيقات الأخرى قبل المتابعة. \n\nانقر على «التالي» للمتابعة، أو «إلغاء» للخروج من برنامج التثبيت.",
        "license": "اتفاقية الترخيص",
        "license_info": "يرجى قراءة اتفاقية الترخيص والموافقة عليها لمتابعة التثبيت",
        "license_agree": "أوافق على شروط اتفاقية الترخيص",
        "path": "اختيار مجلد الوجهة",
        "path_info": "في أي مجلد تريد تثبيت {name}؟",
        "path_agree": "انقر على «التالي» للمتابعة. إذا كنت تريد اختيار مجلد آخر، انقر على «استعراض».",
        "path_size": "مطلوب على الأقل {size} {byts} من مساحة القرص الخالية.",
        "additionally": "اختيار المهام الإضافية",
        "additionally_info": "ما هي المهام الإضافية التي تريد تنفيذها؟",
        "additionally_agree": "اختر المهام الإضافية التي تريد تنفيذها أثناء تثبيت {name}، ثم انقر على «التالي»:",
        "additionally_options": "خيارات إضافية:",
        "additionally-icon": "إنشاء أيقونة على سطح المكتب",
        "additionally-driver": "تثبيت برامج التشغيل المطلوبة",
        "done": "جاهز للتثبيت",
        "done_info": "برنامج التثبيت جاهز الآن لبدء تثبيت {name} على جهاز الكمبيوتر الخاص بك.",
        "done_agree": "انقر على «تثبيت» للمتابعة.",
        "done_agree_tasks": "انقر على «تثبيت» للمتابعة، أو انقر على «رجوع» لمراجعة الإعدادات أو تغييرها.",
        "done_tasks": "مهام إضافية:",
        "installation_info": "يرجى الانتظار أثناء تثبيت {name} على جهاز الكمبيوتر الخاص بك.",
        "installation_agree-install": "جارٍ التثبيت...",
        "installation_agree-install_driver": "جارٍ تثبيت الحزم...",
        "installation_agree-unpacking": "جارٍ استخراج الملفات...",
        "installation_agree-options": "جارٍ تنفيذ الخيارات...",
        "completion": "اكتمال معالج تثبيت {name}",
        "completion_info": "تم تثبيت {name} على جهاز الكمبيوتر الخاص بك.\nيمكن تشغيل التطبيق باستخدام الأيقونة المخصصة.",
        "completion_agree": "انقر على «إنهاء» للخروج من برنامج التثبيت.",
        "completion-icon": "تشغيل {name}",
        "exit": "الخروج من برنامج التثبيت",
        "exit_info": "التثبيت غير مكتمل. إذا خرجت الآن، فلن يتم تثبيت البرنامج.\n\nيمكنك إكمال التثبيت بتشغيل برنامج التثبيت مرة أخرى لاحقًا. \n\nهل تريد الخروج من برنامج التثبيت؟",
        "yes": "نعم",
        "no": "لا",
        "further": "التالي",
        "complete": "إنهاء",
        "install": "تثبيت",
        "cancellation": "إلغاء",
        "back": "رجوع",
        "review": "استعراض...",
        "name": "العربية",
        "units": ["كيلوبايت", "ميغابايت", "غيغابايت", "تيرابايت", "بيتابايت"],
        "byte": "بايت"
    }
}

TRANSLATIONS = [TRANSLATION[i]["name"] for i in TRANSLATION.keys()]

# глобальные изменения темы и языка
def set_TRANSLATION(n):
    global _TRANSLATION
    _TRANSLATION = n

def get_TRANSLATION():
    global _TRANSLATION
    return _TRANSLATION

set_TRANSLATION("ru") # стандарт