import numpy
import math

def degrees_to_radians(deg: float) -> float: ... # приабразуе из градуса в радиант

class _Figur:
    def __init__(self,width_: int, height_: int , position: tuple[int, int, int] = (0.0, 0.0, 0.0)) -> None: ...

    # обнавлние кординат
    def update( distans:float = 0.0) -> None: ...

    #TODO: Реализовать отрисовку в Python
    def _draw(start: tuple[int], end: tuple[int]) -> None: ...
    def draw() -> None: ...

    #повороты по осям
    def turn_y(rads: float) -> None: ...
    def turn_x(rads: float) -> None: ...
    def turn_z(rads: float) -> None: ...

    #установка кординат
    def set_vertices(vertices: numpy.array[list[list[float, float, float]]]) -> None: ...
    def set_edges(new_edges:numpy.array[list[list[int, int]]]) -> None: ...
    def set_position(position: list[float, float, float]) -> None: ...
    
    def set_fov(_fov: int = 5) -> None: ...
    def set_height_width(width_: int, height_: int) -> None: ...

    def get_projected_vertices() ->  list[list[int, int, int]]: ...
    def get_edges() -> numpy.array[list[list[int, int]]]: ...